// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ObjectWebApi.Migrations
{
    [DbContext(typeof(ObjectDbContext))]
    partial class ObjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.CustomObjectDbM", b =>
                {
                    b.Property<Guid>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("ObjectId");

                    b.ToTable("CustomObjects");
                });

            modelBuilder.Entity("DbModels.ObjectPropertiesDbM", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomObjectDbMObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("PropertyId");

                    b.HasIndex("CustomObjectDbMObjectId");

                    b.ToTable("ObjectProperties");
                });

            modelBuilder.Entity("DbModels.ObjectPropertiesDbM", b =>
                {
                    b.HasOne("DbModels.CustomObjectDbM", "CustomObjectDbM")
                        .WithMany("ObjectPropertiesDbM")
                        .HasForeignKey("CustomObjectDbMObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomObjectDbM");
                });

            modelBuilder.Entity("DbModels.CustomObjectDbM", b =>
                {
                    b.Navigation("ObjectPropertiesDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
